Add link to appointment booking api and clear some empty pages.
iuec/uec-tech-standards pull request #4
Opened 2018-12-05 17:04 UTC by afzalmufti

Small change, commenting out menu links to some empty pages pending new content being developed.

Staging link: https://developer-test.nhs.uk/apis/uec-tech-standards/appointments.html

2018-12-05 20:40 UTC, mattstibbs commented
Thanks @afzalmufti 

Could you update the link to appointments documentation to be **https://developer.nhs.uk/apis/uec-appointments** please

2018-12-05 20:46 UTC, mattstibbs requested changes
Please update appointments URL as per comment

2018-12-05 20:46 UTC, mattstibbs commented on _pages/emerging/appointments.md
> +[Access the appointment booking API documentation](https://nhsd-a2si.github.io/docs-uec-appts/)
Please update this link to https://developer.nhs.uk/apis/uec-appointments/

2018-12-05 23:27 UTC, afzalmufti commented
URL amended, should be good to go now. Thanks!

2018-12-07 15:06 UTC, mattstibbs approved these changes

2018-12-07 15:07 UTC, merged